# Spring Boot configuration
spring:
  profiles:
    active: development
  # Security configuration
  security:
    user:
      name: user
      password: user
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# JSF configuration
jsf:
  urlMappings: "*.xhtml"
  facesServletName: Faces Servlet
  servletContext: 
    forceLoadConfigurationParam: com.sun.faces.forceLoadConfiguration
    forceLoadConfigurationValue: true
    primefaces: 
      themeParam: primefaces.THEME
      themeValue: nova-light #bootstrap
      clientSideValidationParam: primefaces.CLIENT_SIDE_VALIDATION
      clientSideValidationValue: true
      fontParam: primefaces.FONT_AWESOME
      fontValue: true
  faceletsSkipCommentsParam: javax.faces.FACELETS_SKIP_COMMENTS
  faceletsSkipCommentsValue: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    '[org.springframework]': info
    '[org.hibernate.sql]': debug
# Server configuration
server:
  port: 7070 #set your port
  servlet:
    context-path: /demoJSF